config/routes.rb
Rails.application.routes.draw do
  resources :cities
  root 'sessions#new'

  get 'sessions/index' => "sessions#index"
  get '/logout' => 'sessions#destroy'
  get 'dashboard/index' => "dashboard#index"
  get 'cities' => "cities#index"
  resource :sessions
  resource :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :cities 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end
  def require_logged_in
    return true if current_user

    return redirect_to dasboard_index_path
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = current_user.cities
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = current_user.cities.build(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_index_path, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController


  def index
    @cities = current_user.cities
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.
            find_by(username: params[:username]).
            try(:authenticate, params[:password])

    return render action: 'new' unless @user

    #logged in
    session[:user_id] = @user.id
    redirect_to dashboard_index_path
  end
  def destroy
    session[:user_id] = nil

    # reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    return render action: 'new' unless @user.save

    redirect_to root_path, notice: 'Created user'
  end

  private
  def user_params
    params.
      require(:user).
      permit(:username,
             :password,
             :password_confirmation)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/_form.html.erb
<body class="profile-img3">


<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-6 col-md-offset-3 login">
<div class="form-group">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :city_name, class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>
</body>

app/views/cities/_index.html.erb
<p id="notice"><%= notice %></p>
<div class="logout-new-city">
<%= link_to 'Add New City', new_city_path, class: 'btn btn-info' %>
<%= link_to "Logout", '/logout', class: 'btn btn-info submit' %>
</div>

<center><h1 class="fav-city">Favorite Cities</h1></center>
<body class="profile-img">

  <div class="col-xs-12">

    <% @cities.each do |city| %>

    <div class="col-md-6 col-lg-4" style="margin-bottom: 25px;">
      <div class="card city-card-top">

        <h4 class="card-title"><center><%= city.name %></h4></center>
        <br>
      </div>
      <div class="card city-card-bottom">
        <div class="card-block">

        <% weather = WeatherService.get_city_weather(city.name)%>
          <p class="card-text"><span class="sub"><%= image_tag ("http://openweathermap.org/img/w/#{weather['weather'][0]['icon']}.png") %></p>
          <p class="card-text"><span class="sub"><%= weather['main']['temp']%>&deg;F</strong></p>
          <p class="card-text"><span class="sub"><%= weather['weather'][0]['description']%></strong></p>
          <p class="card-text"><span class="sub">Pressure: <%= weather['main']['pressure']%> hPa</strong></p>
          <p class="card-text"><span class="sub">Humidity: <%= weather['main']['humidity']%>%</strong></p>
          <p class="card-text"><span class="sub">Min Temperature: <%= weather['main']['temp_min']%>&deg;F</strong></p>
          <p class="card-text"><span class="sub">Max Temperature: <%= weather['main']['temp_max']%>&deg;F</strong></p>
          <%= link_to 'Show', city, class: 'btn btn-info' %>
            <%= link_to 'Edit', edit_city_path(city), class: 'btn btn-info' %>
            <%= link_to 'Destroy', city, class: 'btn btn-info', method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>

    <% end %>


</div>





</body>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', dashboard_index_path %>

app/views/cities/new.html.erb
<center><h1 class="new-city">New City</h1></center>

<%= render 'form', city: @city %>

<%= link_to 'Back', dashboard_index_path %>

app/views/cities/show.html.erb
<body class="blue-sky">

<p id="notice"><%= notice %></p>

<script   src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
  <h1 class="city-header"><strong><%= @city.name %></strong></h1>

  <% weather = WeatherService.get_city_weather(@city.name)%>

  <p class="temp"><%= weather['main']['temp']%>&deg;F</p>
  <p class="icon"><%= image_tag ("http://openweathermap.org/img/w/#{weather['weather'][0]['icon']}.png") %></p>
  <p class="temp"><%= weather['weather'][0]['description']%></p>
  <p class="info">Sunrise:<%= Time.at(weather['sys']['sunrise']).strftime("%I:%M%p")%></p>
  <p class="info">Sunset:<%= Time.at(weather['sys']['sunset']).strftime("%I:%M%p")%></p>
  <p class="info">Pressure:<%= weather['main']['pressure']%> hPa</p>
  <p class="info">Humidity:<%= weather['main']['humidity']%>%</p>
  <p class="info">Wind:<%= weather['wind']['speed']%>mph</p>
  <p class="info">Min Temperature:<%= weather['main']['temp_min']%>&deg;F</p>
  <p class="info">Max Temperature:<%= weather['main']['temp_max']%>&deg;F</p>

</p>
<button type="button" onclick="$('body').toggleClass('blue-sky night-sky');" name="button">Click me!</button>

<button type="button"><%= link_to 'Edit', edit_city_path(@city) %></button> |
<button type="button"><%= link_to 'Back', dashboard_index_path %></button>
</body>

app/views/dashboard/index.html.erb
<%= render 'cities/index', cities: @cities %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weatherapp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


    <%= yield %>

</html>

app/views/users/new.html.erb
<body class="login-img">

  <div class="col-md-6 col-md-offset-3 login">
<center><h1>Sign up</h1></center>
<%= form_for @user do |f| %>
<div class="form-group">
<%= f.label :username %>
<%= f.text_field :username, class: 'form-control' %>
</div>
<div class="form-group">
<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>
</div>
<div class="form-group">
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation, class: 'form-control' %>
</div>
<p>
<center><%= f.submit %></center><br>
<center><%= link_to 'back', root_path, class: 'btn btn-info btn-default' %></center>
</p>
<% end %>

</div>
</body>